services:
  app:
    build:
      context: .
    secrets:
      - db_root_password
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: compose.yaml
  node:
    image: node
    working_dir: /app
    volumes:
      - ./src:/app
    command: ["tail", "-f", "/dev/null"]
secrets:
  db_root_password:
    file: db_root_password.txt